#!/usr/bin/env bash
# The catalog gardener's deterministic core: SCHEMA.md generated from live schema + COMMENT ON,
# with sample rows per table (schema-in-context reduces agent hallucination — research-traversal).
# Runs as a migration-runner hook: schema changes only happen via migrations (P9).
set -euo pipefail

PG_BIN="${PG_BIN:-/opt/homebrew/opt/postgresql@17/bin}"
export PGHOST="${PGHOST:-$HOME/.claudio/sock}" PGPORT="${CLAUDIO_PGPORT:-5433}"
DB="claudio"
REPO="$(cd "$(dirname "$0")/../../.." && pwd)"
OUT="$REPO/SCHEMA.md"
PSQL=("$PG_BIN/psql" -U postgres -d "$DB" -tA -v ON_ERROR_STOP=1)

{
  echo "# SCHEMA.md — generated catalog ($(date +%Y-%m-%d))"
  echo
  echo "Generated by core/pipes/catalog/generate.sh on every migration. Do not edit; edit COMMENT ON in migrations."
  echo

  for t in $("${PSQL[@]}" -c "select tablename from pg_tables where schemaname='l1' and tablename <> 'migrations' order by tablename"); do
    echo "## l1.$t"
    echo
    desc="$("${PSQL[@]}" -c "select coalesce(obj_description('l1.$t'::regclass), '')")"
    [ -n "$desc" ] && echo "$desc" && echo
    echo '```'
    "${PSQL[@]}" -c "select column_name || ' ' || data_type ||
                     coalesce(' [' || col_description('l1.$t'::regclass, ordinal_position) || ']', '')
                     from information_schema.columns
                     where table_schema='l1' and table_name='$t' order by ordinal_position"
    echo '```'
    echo
    n="$("${PSQL[@]}" -c "select count(*) from l1.\"$t\"")"
    if [ "$n" -gt 0 ]; then
      echo "Sample rows ($n total):"
      echo '```'
      "$PG_BIN/psql" -U postgres -d "$DB" -v ON_ERROR_STOP=1 -P border=0 -c "select * from l1.\"$t\" limit 2" | head -20
      echo '```'
      echo
    fi
  done

  echo "## L1 functions"
  echo
  "${PSQL[@]}" -F'|' -c "
    select '### l1.' || p.proname || '(' || pg_get_function_identity_arguments(p.oid) || ')' || E'\n\n' ||
           coalesce(obj_description(p.oid), '(no comment yet)') || E'\n'
    from pg_proc p join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'l1' and p.proname not like 'tg\\_%'
    order by p.proname"
} > "$OUT"

echo "wrote $OUT"
